FROM ruby:2.7.2

ENV TZ=America/Sao_Paulo
ENV APP_PATH /app-exemplo
ENV BUNDLER_VERSION=2.4.5

RUN apt-get update -qq && apt-get upgrade -y && \
  apt-get install -y \
  libpq-dev \
  nodejs \
  npm \
  yarn \
  libghc-qrencode-prof \
  zlib1g-dev \
  libghc-qrencode-dev \
  --no-install-recommends \
  && rm -rf /var/lib/apt/lists/*

RUN gem install bundler -v $BUNDLER_VERSION

WORKDIR $APP_PATH
COPY . .

COPY Gemfile Gemfile.lock ./

ENV BUNDLE_PATH /gems
RUN bundle check || bundle install
RUN npm install --global yarn && yarn install --check-files

EXPOSE 3000

ENTRYPOINT ["bundle", "exec"]

CMD ["rails", "server", "-b", "0.0.0.0"]
