default: &default
  adapter: postgresql
  encoding: unicode
  host: postgresql
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: password

development:
  <<: *default
  database: app-exemplo_development
test:
  <<: *default
  database: app-exemplo_test
  
production:
  <<: *default
  database: app-exemplo_production
  username: socialm
  password: <%= ENV["SOCIALM_DATABASE_PASSWORD"] %>